theme: jekyll-theme-slate

title: Tim Morris
description: "I’m a quality engineer that enjoys merging my experience from both technical and commercial roles to deliver great software. Here are a few Python/JavaScript tools that I’ve created along the way."

