theme: jekyll-theme-slate

title: Tim Morris
description: "I’m a quality engineer that enjoys merging my experience from both technical and commercial roles. Here are a few Python/Javascript tools that I’ve created along the way."

